### ISSUE TITLE
Measure arguments are not repeatable

### ISSUE THREAD

**Issue by macumber** [tsbyq/openstudio-occupant-variability-gem#2]
Methods `model.getSpaceTypes` and `space_type.spaces` do not return objects in a sorted order.  Therefore there is no guarantee that this code will  assign the same index to each space if run multiple times:

https://github.com/tsbyq/openstudio-occupant-variability-gem/blob/master/lib/measures/Occupancy_Simulator/measure.rb#L168

I suggest dropping the `Space_#{i}_` prefix as space names are already guaranteed to be unique.  If you want to keep it, you'll want to sort the spaces and spacetypes by name before looping over them.  Also, measure argument names (not the display names) can't have spaces in them due to constraints in OpenStudio server.   Suggest using `gsub` to replace spaces and other characters in space names when creating argument names.

**Comment by tsbyq** [comment]
Thanks for the suggestion. The prefix was to keep the style consistent as occupancy simulator XML template. It is now removed. The `gsup` method is used to get rid of potential white-space in the argument names, too.
