### ISSUE TITLE
Measure should write to current dir, not measure resources dir

### ISSUE THREAD

**Issue by macumber** [tsbyq/openstudio-occupant-variability-gem#3]
When writing files, measure should write to the current dir `./` rather than the measure resource dir:

https://github.com/tsbyq/openstudio-occupant-variability-gem/blob/master/lib/measures/Occupancy_Simulator/measure.rb#L1079

If multiple instances of the measure are run in parallel they will overwrite each other in the measure resource dir.

**Comment by tsbyq** [comment]
Three measures: 1. occupancy_simulator, 2. create_lighting_schedule_from_people_count, and 3. create_MELs_schedule_from_people_count are updated so that the CSV schedule files are written into the measure root paths instead of their resources dir.

**Comment by tsbyq** [comment]
Updated in this [PR](https://github.com/tsbyq/openstudio-occupant-variability-gem/pull/7). Write files into the current run dir instead of measure folder or its sub-folders.
